/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.hdsb.gwss.youssef.ics4u.u3;

/**
 *
 * @author Youss
 */
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import java.util.StringTokenizer;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;
import org.jfree.ui.ApplicationFrame;
import org.jfree.ui.RefineryUtilities;

public class MountainPathsGraph extends ApplicationFrame {

    /**
     * A demonstration application showing an XY series containing a null value.
     *
     * @param title the frame title.
     * @throws java.io.FileNotFoundException
     */
    public MountainPathsGraph(final String title) throws FileNotFoundException {
        super(title);
        final XYSeries series = new XYSeries("Elevation Change");
        
        int i = -1;
        int j;

        int row = 1;
        int col = 0;

        Scanner read = new Scanner(new File(".\\data\\mountain.paths\\Colorado.844x480.dat"));
        StringTokenizer st = new StringTokenizer(read.nextLine());

        while (st.hasMoreTokens()) {
            st.nextToken();
            col++;
        }

        while (read.hasNextLine()) {
            read.nextLine();
            row++;
        }

        read = new Scanner(new File(".\\data\\mountain.paths\\Colorado.844x480.dat"));
        int[][] data2 = new int[row][col];

        while (read.hasNextLine()) {
            j = -1;
            i++;
            st = new StringTokenizer(read.nextLine());
            while (st.hasMoreTokens()) {
                j++;
                data2[i][j] = Integer.parseInt(st.nextToken());
            }
        }
        
            for (int l = 0; l < data2.length; l++) {
                series.add(l, data2[11][l]);
            }
        

        final XYSeriesCollection data = new XYSeriesCollection(series);
        final JFreeChart chart = ChartFactory.createXYLineChart(
                "Difference in Elevation",
                "Column",
                "Elevation",
                data,
                PlotOrientation.VERTICAL,
                true,
                true,
                false
        );

        final ChartPanel chartPanel = new ChartPanel(chart);
        chartPanel.setPreferredSize(new java.awt.Dimension(500, 270));
        setContentPane(chartPanel);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     * @throws java.io.FileNotFoundException
     */
    public static void main(final String[] args) throws FileNotFoundException {

        final MountainPathsGraph demo = new MountainPathsGraph("XY Series Demo");
        demo.pack();
        RefineryUtilities.centerFrameOnScreen(demo);
        demo.setVisible(true);

    }

}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

