/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ca.hdsb.gwss.youssef.ics3u.u8;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import nu.xom.Builder;
import nu.xom.Document;
import nu.xom.Element;
import nu.xom.Elements;
import nu.xom.ParsingException;
import nu.xom.Serializer;

/**
 *
 * @author 1mohamedyou
 */
public class AddPage extends javax.swing.JFrame {

    Element root;
    Document doc;

    Element type;

    SplashPage parent;
    DisplayPage sibling;

    /**
     * Creates new form AddPage
     *
     * @param parent
     */
    public AddPage(SplashPage parent) {
        initComponents();
        this.parent = parent;

        File file = new File("marks.xml");

        if (file.exists()) {

            Builder builder = new Builder();
            try {
                doc = builder.build(file);
                root = doc.getRootElement();
            } catch (IOException | ParsingException ex) {
                Logger.getLogger(AddPage.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            root = new Element("year");
            doc = new Document(root);
        }

        Element semester;

        semester = new Element("semester");
        root.appendChild(semester);

        Element subject = new Element("computerScience");
        Element subjectName = new Element("subjectName");
        organizeSubject(subject);
        subject.appendChild(subjectName);
        subjectName.appendChild("Computer Science");
        semester.appendChild(subject);

        subject = new Element("chemistry");
        subjectName = new Element("subjectName");
        organizeSubject(subject);
        subject.appendChild(subjectName);
        subjectName.appendChild("Chemistry");
        semester.appendChild(subject);

        subject = new Element("functions");
        subjectName = new Element("subjectName");
        organizeSubject(subject);
        subject.appendChild(subjectName);
        subjectName.appendChild("Functions");
        semester.appendChild(subject);

        subject = new Element("accounting");
        subjectName = new Element("subjectName");
        organizeSubject(subject);
        subject.appendChild(subjectName);
        subjectName.appendChild("Accounting");
        semester.appendChild(subject);

        semester = new Element("semester");
        root.appendChild(semester);

        subject = new Element("english");
        subjectName = new Element("subjectName");
        organizeSubject(subject);
        subject.appendChild(subjectName);
        subjectName.appendChild("English");
        semester.appendChild(subject);

        subject = new Element("manufacturing");
        subjectName = new Element("subjectName");
        organizeSubject(subject);
        subject.appendChild(subjectName);
        subjectName.appendChild("Manufacturing");
        semester.appendChild(subject);

        subject = new Element("physics");
        subjectName = new Element("subjectName");
        organizeSubject(subject);
        subject.appendChild(subjectName);
        subjectName.appendChild("Physics");
        semester.appendChild(subject);

        subject = new Element("computerEngineering");
        subjectName = new Element("subjectName");
        organizeSubject(subject);
        subject.appendChild(subjectName);
        subjectName.appendChild("Computer Engineering");
        semester.appendChild(subject);

        setUpComboBox();
    }

    public void setSibling(DisplayPage d) {
        this.sibling = d;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sem = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();
        jComboBox2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        title.setText("Add Marks");

        jButton2.setText("Done");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Semester:");

        jLabel3.setText("Subject:");

        jLabel4.setText("Name:");

        jLabel5.setText("Grade:");

        jLabel7.setText("Type:");

        jTextField4.setText("Data Structures");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setToolTipText("");
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        sem.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("1");
        jRadioButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton1MouseClicked(evt);
            }
        });

        sem.add(jRadioButton2);
        jRadioButton2.setText("2");
        jRadioButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton2MouseClicked(evt);
            }
        });

        jButton3.setText("Display");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 100.0d, 0.1d));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.setToolTipText("");
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton3)))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSpinner1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(title))
                            .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void setUpComboBox() {
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>());
        Element subject;
        String name;

        Elements year = root.getChildElements();
        Elements subjects = year.get(0).getChildElements();
        for (int i = 0; i < subjects.size(); i++) {
            subject = subjects.get(i);
            name = subject.getFirstChildElement("subjectName").getValue();
            jComboBox1.addItem(name);
        }
    }

    private void organizeSubject(Element subject) {

        type = new Element("unitTests");
        subject.appendChild(type);
        type = new Element("quizzes");
        subject.appendChild(type);
        type = new Element("assignments");
        subject.appendChild(type);
        type = new Element("other");
        subject.appendChild(type);

    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean lettersOnly = true;
        try {
            Element name = new Element(jTextField4.getText().replaceAll(" ", ""));
        } catch (Exception e) {
            lettersOnly = false;
        }

        if (lettersOnly) {
            Element name = new Element(jTextField4.getText().replaceAll(" ", ""));
            Element grade = new Element("grade");

            type.appendChild(name);
            name.appendChild(grade);
            grade.appendChild(jSpinner1.getValue().toString());

            try {
                Serializer serializer = new Serializer(System.out);
                serializer.setIndent(4);
                serializer.setMaxLength(64);
                serializer.write(doc);
            } catch (IOException ex) {
                System.err.println(ex);
            }

            try {
                FileWriter fw = new FileWriter("marks.xml");
                try (BufferedWriter output = new BufferedWriter(fw)) {
                    output.write(doc.toXML());
                }
            } catch (IOException ex) {
                Logger.getLogger(AddPage.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            jTextField4.setText("Letters Only.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        this.parent.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.setVisible(false);
        this.sibling.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jRadioButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton1MouseClicked
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>());
        Element subject;
        String name;

        Elements year = root.getChildElements();
        Elements subjects = year.get(0).getChildElements();
        for (int i = 0; i < subjects.size(); i++) {
            subject = subjects.get(i);
            name = subject.getFirstChildElement("subjectName").getValue();
            jComboBox1.addItem(name);
        }
    }//GEN-LAST:event_jRadioButton1MouseClicked

    private void jRadioButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton2MouseClicked
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>());
        Element subject;
        String name;

        Elements year = root.getChildElements();
        Elements subjects = year.get(1).getChildElements();
        for (int i = 0; i < subjects.size(); i++) {
            subject = subjects.get(i);
            name = subject.getFirstChildElement("subjectName").getValue();
            jComboBox1.addItem(name);
        }
    }//GEN-LAST:event_jRadioButton2MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.ButtonGroup sem;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
